# Generated by Django 5.0.6 on 2024-08-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeTable',
            fields=[
                ('age', models.IntegerField(primary_key=True, serialize=False)),
                ('men_survived_to_age', models.IntegerField()),
                ('men_died_at_age', models.IntegerField()),
                ('women_survived_to_age', models.IntegerField()),
                ('women_died_at_age', models.IntegerField()),
            ],
        ),
    ]
